/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/usr"
#define EXEC_PREFIX "/usr"
#define BINDIR "/usr/bin"
#define SBINDIR "/usr/sbin"
#define LIBEXECDIR "/usr/libexec"
#define DATAROOTDIR "/usr/share"
#define DATADIR "/usr/share"
#define SYSCONFDIR "/etc"
#define SHAREDSTATEDIR "/var"
#define LOCALSTATEDIR "/var"
#define RUNSTATEDIR "/var/run"
#define INCLUDEDIR "/usr/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/usr/share/doc/coreutils"
#define INFODIR "/usr/share/info"
#define HTMLDIR "/usr/share/doc/coreutils"
#define DVIDIR "/usr/share/doc/coreutils"
#define PDFDIR "/usr/share/doc/coreutils"
#define PSDIR "/usr/share/doc/coreutils"
#define LIBDIR "/usr/lib64"
#define LISPDIR "/usr/share/emacs/site-lisp"
#define LOCALEDIR "/usr/share/locale"
#define MANDIR "/usr/share/man"
#define PKGDATADIR "/usr/share/coreutils"
#define PKGINCLUDEDIR "/usr/include/coreutils"
#define PKGLIBDIR "/usr/lib64/coreutils"
#define PKGLIBEXECDIR "/usr/libexec/coreutils"
