.TH "wl_cursor_theme" 3 "Version 1.24.90" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_cursor_theme
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBcursor_count\fP"
.br
.ti -1c
.RI "struct \fBwl_cursor\fP ** \fBcursors\fP"
.br
.ti -1c
.RI "struct wl_shm * \fBshm\fP"
.br
.ti -1c
.RI "struct \fBshm_pool\fP * \fBpool\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int wl_cursor_theme::cursor_count"

.SS "struct \fBwl_cursor\fP** wl_cursor_theme::cursors"

.SS "struct \fBshm_pool\fP* wl_cursor_theme::pool"

.SS "struct wl_shm* wl_cursor_theme::shm"

.SS "int wl_cursor_theme::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
